#+OPTIONS: num:nil toc:t H:4
#+OPTIONS: html-preamble:nil html-postamble:nil html-scripts:t html-style:nil
#+TITLE: Album List

#+DESCRIPTION: Album List
#+KEYWORDS: Album List
#+HTML_HEAD_EXTRA: <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
#+HTML_HEAD_EXTRA: <link rel="icon" href="images/favicon.ico" type="image/x-icon">
#+HTML_HEAD_EXTRA:  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
#+HTML_HEAD_EXTRA:  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
#+HTML_HEAD_EXTRA:  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
#+HTML_HEAD_EXTRA:  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
#+HTML_HEAD_EXTRA:  <script src="js/elementSearch.js"></script>
#+HTML_HEAD_EXTRA:  <link rel="stylesheet" href="css/main.css">
#+HTML_HEAD_EXTRA:  <link rel="stylesheet" href="css/blog.css">
#+HTML_HEAD_EXTRA: <style>body { padding-top: 100px; }</style>

* Album List
  :PROPERTIES:
  :HTML_CONTAINER_CLASS: text-center navbar navbar-inverse navbar-fixed-top
  :CUSTOM_ID: navbar
  :END:

  #+BEGIN_EXPORT html
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapsableNavbar">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <h1 id="navbarTitle" class="navbar-text">Album List</h1>
      <div class="collapse navbar-collapse" id="collapsableNavbar">
      <ul class="nav navbar-nav">
      <li><a title="Home" href="./index.html"><i class="fas fa-home fa-3x" aria-hidden="true"></i></a></li>
      <li><a title="Blog Main Page" href="./blog.html" class="navbar-text h3">Blog</a></li>
      <li><a title="Article List" href="./articleList.html" class="navbar-text h3">Article List</a></li>
<li><a title="Book List" href="./bookList.html" class="navbar-text h3">Book List</a></li>
    <li><a title="Note Trainer" href="./NoteTrainer/NoteTrainer.html" class="navbar-text h3">Note Trainer</a></li>
      </ul>
      </div>
  #+END_EXPORT


* Albums
  :PROPERTIES:
  :CUSTOM_ID: Albums
  :END:

  **Created:** <2020-06-21 Sun>

  #+BEGIN_EXPORT HTML
  <p style="text-align: center">Next Up Music Playlist</p>
  <iframe src="https://www.youtube.com/embed/videoseries?list=PLO1i4nEhzCLaszits0vM6cJJoCIqzTwn7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" style="display: block;width: 80%;margin-left: auto;margin-right: auto;" allowfullscreen></iframe>
  <input type="text" id="elementSearch" onkeyup="elementSearch('albumList')" placeholder="Search for albums.." title="Type in a Album Title" style="text-align: center; width: 80%;margin-left: auto;margin-right: auto; display: block;">
  <p id="totalAlbumCount"></p>
  <ul id="albumList"                                                                                                  class="list-group">
      <a target="_blank" href="https://youtu.be/QnXOSUQ5HJY"                                                          class="list-group-item list-group-item-action album">AC/DC - Back In Black</a>
      <a target="_blank" href="https://youtu.be/oID_yTTx7gQ"                                                          class="list-group-item list-group-item-action album">All That Remains - Overcome</a>
      <a target="_blank" href="https://youtu.be/BOu3bAYxYAA"                                                          class="list-group-item list-group-item-action album">All That Remains - The Fall of Ideals</a>
      <a target="_blank" href="https://youtu.be/puEBsz4TDBE"                                                          class="list-group-item list-group-item-action album">Amon Amarth - Jomsviking</a>
      <a target="_blank" href="https://youtu.be/cqqv24yGoeo"                                                          class="list-group-item list-group-item-action album">Annihilator - Carnival Diablos</a>
      <a target="_blank" href="https://youtu.be/T9TtmYCPCLU"                                                          class="list-group-item list-group-item-action album">Annihilator - Criteria for a Black Widow</a>
      <a target="_blank" href="https://youtu.be/KO5ad84UixQ"                                                          class="list-group-item list-group-item-action album">Annihilator - King of the Kill</a>
      <a target="_blank" href="https://youtu.be/W_b4FAtoDV4"                                                          class="list-group-item list-group-item-action album">Annihilator - Metal</a>
      <a target="_blank" href="https://youtu.be/PpieGB80EqU"                                                          class="list-group-item list-group-item-action album">Arch Enemy - Doomsday Machine</a>
      <a target="_blank" href="https://youtu.be/2-fR2rrmw3I"                                                          class="list-group-item list-group-item-action album">Arch Enemy - War Eternal</a>
      <a target="_blank" href="https://youtu.be/bl0QVeD-KJg"                                                          class="list-group-item list-group-item-action album">As I Lay Dying - An Ocean Between Us</a>
      <a target="_blank" href="https://youtu.be/1xtedxA8ehM"                                                          class="list-group-item list-group-item-action album">Aspherium - The Embers of Eternity</a>
      <a target="_blank" href="https://youtu.be/KhL4lK3uoYo"                                                          class="list-group-item list-group-item-action album">At The Gates - Slaughter Of The Soul [Bonus Tracks]</a>
      <a target="_blank" href="https://youtu.be/DVDHXx_cIu8"                                                          class="list-group-item list-group-item-action album">Atreyu - Lead Sails Paper Anchor</a>
      <a target="_blank" href="https://youtu.be/9UTGl_LnnKc"                                                          class="list-group-item list-group-item-action album">Avenged Sevenfold - City of Evil</a>
      <a target="_blank" href="https://youtube.com/playlist?list=PLY1a1INoMkejOjrgpq7m0aFx6P-s75FJa"                  class="list-group-item list-group-item-action album">Born Of Osiris - The Simulation</a>
      <a target="_blank" href="https://youtu.be/NB7Zb9QVklE"                                                          class="list-group-item list-group-item-action album">Death - The Sound Of Perseverance</a>
      <a target="_blank" href="https://youtu.be/yKM3Shq-JyI"                                                          class="list-group-item list-group-item-action album">Deep Purple - Machine Head</a>
      <a target="_blank" href="https://youtube.com/playlist?list=PL079F019399AD0059"                                  class="list-group-item list-group-item-action album">Dethklok - The Dethalbum</a>
      <a target="_blank" href="https://youtu.be/s3HYrXaWPGo"                                                          class="list-group-item list-group-item-action album">Dimmu Borgir - Puritanical Euphoric Misanthropia</a>
      <a target="_blank" href="https://youtu.be/hqx6iOs_yIA"                                                          class="list-group-item list-group-item-action album">Dream Theater - Images And Words</a>
      <a target="_blank" href="https://youtu.be/ZV3lCOMP060"                                                          class="list-group-item list-group-item-action album">Extreme - Pornograffitti</a>
      <a target="_blank" href="https://youtu.be/naElQtYgmn4"                                                          class="list-group-item list-group-item-action album">Fleshgod Apocalypse - King</a>
      <a target="_blank" href="https://youtube.com/playlist?list=PLDj6h6txk-4V2HaAPBeK7oEE9pWjHCk7d"                  class="list-group-item list-group-item-action album">Ghostbusters: Original Soundtrack Album<a target="_blank" href="https://youtu.be/f_T8v8imSV4"                                                          class="list-group-item list-group-item-action album">Holy Diver - Dio</a>
      <a target="_blank" href="https://youtu.be/f8hc3odWo5k"                                                          class="list-group-item list-group-item-action album">Guns N' Roses - Appetite For Destruction</a>
      <a target="_blank" href="https://youtu.be/vutytgFZ7W0"                                                          class="list-group-item list-group-item-action album">Haken - The Mountain</a>
      <a target="_blank" href="https://youtu.be/0Bg8oo7PZVY"                                                          class="list-group-item list-group-item-action album">Haken - Visions</a>
      <a target="_blank" href="https://youtu.be/IMeJ5br9jGA"                                                          class="list-group-item list-group-item-action album">I Built The Sky - The Zenith Rise</a>
      <a target="_blank" href="https://youtu.be/y1qRJDmUgRA"                                                          class="list-group-item list-group-item-action album">Ihsahn - Amr</a>
      <a target="_blank" href="https://youtube.com/results?search_query=Ghostbusters:+Original+Soundtrack+Album+-+V+" class="list-group-item list-group-item-action album">In Flames - The Jester Race (Reissue 2014)</a>
      <a target="_blank" href="https://youtu.be/Dw3SdOFmubU"                                                          class="list-group-item list-group-item-action album">Intervals - Circadian</a>
      <a target="_blank" href="https://youtu.be/K0najyrwX6c"                                                          class="list-group-item list-group-item-action album">Jason Kui - Naka</a>
      <a target="_blank" href="https://youtube.com/playlist?list=PLYPKApk7wp1cHaC-RpMaeCKQ0AuxubVzx"                  class="list-group-item list-group-item-action album">Joe Satriani - Surfing With The Alien</a>
      <a target="_blank" href="https://youtu.be/-84b8WcPTWo"                                                          class="list-group-item list-group-item-action album">Joe Satriani - The Extremist</a>
      <a target="_blank" href="https://youtube.com/playlist?list=PLLy1F0NPv5goxCeZNBO4DiU_dbxS_knxg"                  class="list-group-item list-group-item-action album">John Petrucci - Suspended Animation</a>
      <a target="_blank" href="https://youtu.be/lwPebRYeJTo"                                                          class="list-group-item list-group-item-action album">Judas Priest - Painkiller</a>
      <a target="_blank" href="https://youtu.be/3qydyLXGnZU"                                                          class="list-group-item list-group-item-action album">Killswitch Engage - Alive Or Just Breathing</a>
      <a target="_blank" href="https://youtu.be/1WsQEsfZNco"                                                          class="list-group-item list-group-item-action album">Kreator - Enemy Of God</a>
      <a target="_blank" href="https://youtu.be/hJ8sErDmJ8k"                                                          class="list-group-item list-group-item-action album">Lamb Of God - Ashes Of The Wake</a>
      <a target="_blank" href="https://youtu.be/o0-U7A4gLWc"                                                          class="list-group-item list-group-item-action album">Lamb Of God - Sacrament</a>
      <a target="_blank" href="https://youtu.be/P54nRU3-jfk"                                                          class="list-group-item list-group-item-action album">Lari Basilio - Your Love</a>
      <a target="_blank" href="https://youtu.be/hMCVe0cs4DI"                                                          class="list-group-item list-group-item-action album">Luca Mantovanelli - Multiversum</a>
      <a target="_blank" href="https://youtu.be/K6LA7v1PApU"                                                          class="list-group-item list-group-item-action album">Magic Pie - The Suffering Joy</a>
      <a target="_blank" href="https://youtu.be/q9PlPdmX9fE"                                                          class="list-group-item list-group-item-action album">Megadeth - Cryptic Writings [Remaster]</a>
      <a target="_blank" href="https://youtu.be/0FyHXlBsZbs"                                                          class="list-group-item list-group-item-action album">Megadeth - Rust In Peace</a>
      <a target="_blank" href="https://youtube.com/playlist?list=PLjud9YtAo4wnCgSm0hlTbVxhvrdm82-KL"                  class="list-group-item list-group-item-action album">Meshuggah - I</a>
      <a target="_blank" href="https://youtu.be/Tvu4YgxmtPw"                                                          class="list-group-item list-group-item-action album">Metallica - ...And Justice For All</a>
      <a target="_blank" href="https://jasonkui.bandcamp.com/album/naka"                                              class="list-group-item list-group-item-action album">Metallica - Master Of Puppets</a>
      <a target="_blank" href="https://youtu.be/QNOU4vXu_Ao"                                                          class="list-group-item list-group-item-action album">Metallica - Ride The Lightning</a>
      <a target="_blank" href="https://youtube.com/playlist?list=PL188FE1A560B2A862"                                  class="list-group-item list-group-item-action album">Mr.Big - Lean Into It</a>
      <a target="_blank" href="https://youtu.be/H1MEvSJyO_U"                                                          class="list-group-item list-group-item-action album">Nirvana - Nevermind</a>
      <a target="_blank" href="https://youtu.be/MAnsR_7VYKQ"                                                          class="list-group-item list-group-item-action album">Obscura - Diluvium</a>
      <a target="_blank" href="https://youtu.be/OVwEKr38MzQ"                                                          class="list-group-item list-group-item-action album">Oni - Ironshore</a>
      <a target="_blank" href="https://youtu.be/lTJg4P1zo4E"                                                          class="list-group-item list-group-item-action album">Opeth - Blackwater Park</a>
      <a target="_blank" href="https://youtu.be/N94S9u0kTLA"                                                          class="list-group-item list-group-item-action album">Owane - yeah, whatever</a>
      <a target="_blank" href="https://youtu.be/H0XGswUuZU0"                                                          class="list-group-item list-group-item-action album">Pantera - Cowboys From Hell</a>
      <a target="_blank" href="https://youtu.be/nd2LO02Zw9k"                                                          class="list-group-item list-group-item-action album">Pantera - Vulgar Display Of Power</a>
      <a target="_blank" href="https://youtu.be/Ti_imhKBjXA"                                                          class="list-group-item list-group-item-action album">Paul Gilbert - Space Ship One [Bonus Track]</a>
      <a target="_blank" href="https://youtube.com/playlist?list=PLxy1hNzYBr7W1xxK2dcg-8pLlp4r_7L7o"                  class="list-group-item list-group-item-action album">Paul Wardingham - Assimilate Regenerate</a>
      <a target="_blank" href="https://youtu.be/C4eWSMMZrL4"                                                          class="list-group-item list-group-item-action album">Racer X - Technical Difficulties</a>
      <a target="_blank" href="https://www.youtube.com/playlist?list=OLAK5uy_kvNKgEASt8AiZePGbpYGvgHYA0TBIMpT4"       class="list-group-item list-group-item-action album">Rage Against the Machine - Rage Against the Machine</a>
      <a target="_blank" href="https://youtu.be/614OdhFLUUU"                                                          class="list-group-item list-group-item-action album">Rammstein - Mutter</a>
      <a target="_blank" href="https://youtube.com/playlist?list=PLwl83FtM2x-ebcxmlU80p_ObssTKdALV_"                  class="list-group-item list-group-item-action album">Rammstein - Reise, Reise</a>
      <a target="_blank" href="https://youtu.be/XjB101k2Bog"                                                          class="list-group-item list-group-item-action album">Richard Benson - L''Inferno dei Vivi</a>
      <a target="_blank" href="https://youtu.be/OiZrdL6eGp4"                                                          class="list-group-item list-group-item-action album">Sabaton - The Last Stand</a>
      <a target="_blank" href="https://youtu.be/sm0j33oxav4"                                                          class="list-group-item list-group-item-action album">Stevie Ray Vaughan & Double Trouble - Couldn't Stand The Weather</a>
      <a target="_blank" href="https://youtu.be/IUj6nDs_Mqg"                                                          class="list-group-item list-group-item-action album">Stevie Ray Vaughan & Double Trouble - Texas Flood</a>
      <a target="_blank" href="https://youtu.be/7nCcD_M13Sw"                                                          class="list-group-item list-group-item-action album">Sum 41 - All Killer No Filler</a>
      <a target="_blank" href="https://youtu.be/z7OoXpAORlE"                                                          class="list-group-item list-group-item-action album">Sylosis - Conclusion of an Age</a>
      <a target="_blank" href="https://youtu.be/nVohJKUiK6o"                                                          class="list-group-item list-group-item-action album">System Of A Down - Toxicity</a>
      <a target="_blank" href="https://youtu.be/REtGa3L0XXg"                                                          class="list-group-item list-group-item-action album">The Essential Joe Hisaishi - Dream Songs</a>
      <a target="_blank" href="https://youtu.be/tUuYKBiuo-w"                                                          class="list-group-item list-group-item-action album">The Jimi Hendrix Experience - Smash Hits</a>
      <a target="_blank" href="https://youtu.be/DO61NWKkyWQ"                                                          class="list-group-item list-group-item-action album">Van Halen - 1984</a>
      <a target="_blank" href="https://youtu.be/FTOilfxhwxs"                                                          class="list-group-item list-group-item-action album">Van Halen - Diver Down</a>
      <a target="_blank" href="https://youtu.be/GGNW2AMAqgo"                                                          class="list-group-item list-group-item-action album">Van Halen - Fair Warning</a>
      <a target="_blank" href="https://youtu.be/yLu4GbCUMRI"                                                          class="list-group-item list-group-item-action album">Van Halen - Van Halen II</a>
      <a target="_blank" href="https://youtu.be/PNjiQt1GbH8"                                                          class="list-group-item list-group-item-action album">Van Halen - Van Halen</a>
      <a target="_blank" href="https://youtu.be/9c2Ny3IN1sA"                                                          class="list-group-item list-group-item-action album">Van Halen - Women And Children First</a>
      <a target="_blank" href="https://youtu.be/w3WIa_Z35p0"                                                          class="list-group-item list-group-item-action album">Yngwie J. Malmsteen's Rising Force - Rising Force</a>
  </ul>
#+END_EXPORT

** Wanna Albums
  :PROPERTIES:
  :CUSTOM_ID: WannaAlbums
  :END:

  Legend:
  #+BEGIN_EXPORT HTML
  <ul>
    <li><span style="background-color:red;">Red:</span> means it's digital only, do not purchase if not strictly necessary.</li>
    <li><span style="background-color:blue;">Blue:</span> means the album is already purchased, but it didn't arrive or wasn't archivied yet. Don't buy.</li>
  </ul>
  #+END_EXPORT

  Price source: Bandcamp, Amazon, and Discgos. Price reference with shipment to UK.

  #+BEGIN_EXPORT HTML
  <ul id="wannaAlbumList" class="list-group">
    <a target="_blank" href="https://youtu.be/PQDGuUc-yrk"                                                                              class="list-group-item list-group-item-action wannaAlbum">£18.89 | An Insatiable High - Masayoshi Takanaka</a>
    <a target="_blank" href="https://youtu.be/t2CmTc75Ugg"                                                                              class="list-group-item list-group-item-action wannaAlbum">£11.43 | Antipop - Primus</a>
    <a target="_blank" href="https://www.youtube.com/watch?v=sWlkFqOYnko"                                                               class="list-group-item list-group-item-action wannaAlbum">€13.99 | Ascendancy - Kadinja</a>
    <a target="_blank" href="https://youtu.be/1QCfbbW4NEw"                                                                              class="list-group-item list-group-item-action wannaAlbum"><p style="display:inline;background-color:red;">£7</p>     | Cassini - Sithu Aye</a>
    <a target="_blank" href="https://youtu.be/CQguu2Ke9Oc"                                                                              class="list-group-item list-group-item-action wannaAlbum">£29.97 | Centrifugal Funk - The Mark Varney Project</a>
    <a target="_blank" href="https://youtube.com/playlist?list=PL3ERHH3tuEjNOol2pOaCD_Tv8VAYi8P00"                                      class="list-group-item list-group-item-action wannaAlbum">€57.26 | Ciao 2020 - Various Artist</a>
    <a target="_blank" href="https://www.amazon.com/dp/B00L904YUC/ref=dm_rwp_pur_lnd_albm_unrg"                                         class="list-group-item list-group-item-action wannaAlbum">£13    | Digital Dream Sequence - Trioscapes</a>
    <a target="_blank" href="https://masterbootrecord.bandcamp.com/album/direct-memory-access"                                          class="list-group-item list-group-item-action wannaAlbum">£10    | Direct Memory Access - Master Boot Record</a>
    <a target="_blank" href="https://cloudkicker.bandcamp.com/album/the-discovery"                                                      class="list-group-item list-group-item-action wannaAlbum">£19.37 | The Discovery - Couldkicker</a>
    <a target="_blank" href="https://psycroptic.bandcamp.com/album/divine-council"                                                      class="list-group-item list-group-item-action wannaAlbum">$13.99 | Divine Council - Psycroptic</a>
    <a target="_blank" href="https://steroidpuppets.bandcamp.com/album/earthguest"                                                      class="list-group-item list-group-item-action wannaAlbum"><p style="display:inline;background-color:red;">£8.02</p>  | Earthguest - Steroid Puppets</a>
    <a target="_blank" href="https://cloudkicker.bandcamp.com/album/the-discovery"                                                      class="list-group-item list-group-item-action wannaAlbum"><p style="display:inline;background-color:red;">$7     </p>| The Enigma Division - The Enigma Division</a>
    <a target="_blank" href="https://www.youtube.com/watch?v=9c2Ny3IN1sA"                                                               class="list-group-item list-group-item-action wannaAlbum">$15    | Far More - Lari Basilio</a>
    <a target="_blank" href="https://youtu.be/16EfK9ecjPU"                                                                              class="list-group-item list-group-item-action wannaAlbum">£25.79 | Fear Inoculum - Tool</a>
    <a target="_blank" href="https://tigranhamasyan.bandcamp.com/album/the-call-within"                                                 class="list-group-item list-group-item-action wannaAlbum">£13    | The Call Within - Tigran Hamasyan</a>
    <a target="_blank" href="https://novacollectivefusion.bandcamp.com/album/the-further-side"                                          class="list-group-item list-group-item-action wannaAlbum">£22.01 | The Further Side - Nova Collective</a>
    <a target="_blank" href="https://www.youtube.com/watch?v=KjU4o5cyWS4"                                                               class="list-group-item list-group-item-action wannaAlbum">£16.90 | Gun to Mouth Salvation - Carnal Forge</a>
    <a target="_blank" href="https://masterbootrecord.bandcamp.com/album/interrupt-request"                                             class="list-group-item list-group-item-action wannaAlbum">$10    | Interrupt Request - Master Boot Record</a>
    <a target="_blank" href="https://en.wikipedia.org/wiki/The_Last_in_Line"                                                            class="list-group-item list-group-item-action wannaAlbum">£7.25  | The Last in Line - Dio</a>
    <a target="_blank" href="https://youtu.be/MoJTemOjaw0"                                                                              class="list-group-item list-group-item-action wannaAlbum"><p style="display:inline;background-color:red;">$10    </p>| Natural Evolution - HAAMOJA</a>
    <a target="_blank" href="https://www.youtube.com/watch?v=kt8o5dtNVyk"                                                               class="list-group-item list-group-item-action wannaAlbum">£13.21 | Never Turn Your Back on a Friend - Budgie</a>
    <a target="_blank" href="https://www.youtube.com/watch?v=yXrF0_hoeCA"                                                               class="list-group-item list-group-item-action wannaAlbum">£14    | Mental Violence - Agitator</a>
    <a target="_blank" href="https://www.youtube.com/watch?v=hkj1nt_u2U8"                                                               class="list-group-item list-group-item-action wannaAlbum">£18    | Open Source - Kiko Loureiro</a>
    <a target="_blank" href="https://youtu.be/oiY4zwcjt-s"                                                                              class="list-group-item list-group-item-action wannaAlbum">£10.50 | Relentless Mutation - Archspire</a>
    <a target="_blank" href="https://www.youtube.com/watch?v=r0kgU_cibkU"                                                               class="list-group-item list-group-item-action wannaAlbum">$24    | Spiritual Machines - Paul Wardingham</a>
    <a target="_blank" href="https://www.youtube.com/watch?v=qo2Ji6iNQEE"                                                               class="list-group-item list-group-item-action wannaAlbum">£38.48 | Snarky Puppy (Texas) - We Like It Here</a>
    <a target="_blank" href="https://youtu.be/hpN6nOYEHMk"                                                                              class="list-group-item list-group-item-action wannaAlbum">£11.88 | Unleashing The Shadows - Eletro Nomicon</a>
    <a target="_blank" href="https://youtu.be/WWKFrzNbCq8"                                                                              class="list-group-item list-group-item-action wannaAlbum"><p style="display:inline;background-color:red;">Free</p>   | Volume - Wide Eyes</a>
    <a target="_blank" href="https://youtu.be/WKc-_JGGX2A"                                                                              class="list-group-item list-group-item-action wannaAlbum">£27.80 | The Way Forward - Intervals</a>
  </ul>
#+END_EXPORT

#+begin_export html
<script type="text/javascript">
$(function() {
  $('#text-table-of-contents > ul li').first().css("display", "none");
  $('#text-table-of-contents > ul li:nth-child(2)').first().css("display", "none");
  $('#table-of-contents').addClass("visible-lg")
  $('#totalAlbumCount').text("Total Albums: " + $('.album').length)
});
</script>
#+end_export
