#+OPTIONS: num:nil toc:t H:4
#+OPTIONS: html-preamble:nil html-postamble:nil html-scripts:t html-style:nil
#+TITLE: Book List
#+DESCRIPTION: Book List
#+KEYWORDS: Book List
#+HTML_HEAD_EXTRA: <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
#+HTML_HEAD_EXTRA: <link rel="icon" href="images/favicon.ico" type="image/x-icon">
#+HTML_HEAD_EXTRA:  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
#+HTML_HEAD_EXTRA:  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
#+HTML_HEAD_EXTRA:  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
#+HTML_HEAD_EXTRA:  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
#+HTML_HEAD_EXTRA:  <script src="js/elementSearch.js"></script>
#+HTML_HEAD_EXTRA:  <link rel="stylesheet" href="css/main.css">
#+HTML_HEAD_EXTRA:  <link rel="stylesheet" href="css/blog.css">

#+HTML_HEAD_EXTRA: <style>body { padding-top: 100px; }</style>

* Book List
  :PROPERTIES:
  :HTML_CONTAINER_CLASS: text-center navbar navbar-inverse navbar-fixed-top
  :CUSTOM_ID: navbar
  :END:

  #+BEGIN_EXPORT html
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapsableNavbar">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <h1 id="navbarTitle" class="navbar-text">Book List</h1>
      <div class="collapse navbar-collapse" id="collapsableNavbar">
      <ul class="nav navbar-nav">
      <li><a title="Home" href="./index.html"><i class="fas fa-home fa-3x" aria-hidden="true"></i></a></li>
      <li><a title="Blog Main Page" href="./blog.html" class="navbar-text h3">Blog</a></li>
      <li><a title="Article List" href="./articleList.html" class="navbar-text h3">Article List</a></li>
<li><a title="Album List" href="./albumList.html" class="navbar-text h3">Album List</a></li>
    <li><a title="Note Trainer" href="./NoteTrainer/NoteTrainer.html" class="navbar-text h3">Note Trainer</a></li>
      </ul>
      </div>
  #+END_EXPORT


* Books
  :PROPERTIES:
  :CUSTOM_ID: Books
  :END:

  **Created:** <2020-06-21 Sun>
  [[https://www.goodreads.com/user/show/148546738-enrico-benini][Good Reads Account]]

  #+BEGIN_EXPORT HTML
  <input type="text" id="elementSearch" onkeyup="elementSearch('bookList')" placeholder="Search for Books.." title="Type in an Book Title">
  <p id="totalBookCount"></p>
  <ul id="bookList"                                                                                                                                                   class="list-group">
    <a target="_blank" href="https://www.youtube.com/watch?v=LeZC-nKwKvo"                                                                                             class="list-group-item list-group-item-action book" >1984 <span class="label label-info">Audiobook Ita</span></a>
    <a target="_blank" href="https://youtu.be/BInAElMNUBc"                                                                                                            class="list-group-item list-group-item-action book" >Animal Farm <span class="label label-info">Audiobook Ita</span></a>
    <a target="_blank" href="https://www.youtube.com/playlist?list=PLWWZvkdjkOcxDv-qaMHR-0wwpzFojBEcV"                                                                class="list-group-item list-group-item-action book" >Arsène Lupin, Gentleman-Cambrioleur <span class="label label-info">Audiobook Ita</span></a>
    <a target="_blank" href="https://www.amazon.co.uk/petare-ovvero-manuale-subdolo-artigliere/dp/8898401728"                                                         class="list-group-item list-group-item-action book" >⭐ L'arte di petare ovvero Il manuale del subdolo artigliere</a>
    <a target="_blank" href="https://www.youtube.com/playlist?list=PLO1i4nEhzCLZaCAxS6GyBCVXsh_WgeiFP"                                                                class="list-group-item list-group-item-action book" >Bomba Atomica <span class="label label-info">Audiobook Ita</span></a>
    <a target="_blank" href="https://www.amazon.it/dp/8832757001/?coliid=I1PKWAF03M8ZNY&colid=22QBHENP44UR0&psc=1&ref_=lv_ov_lig_dp_it"                               class="list-group-item list-group-item-action book" >Belzebubs</a>
    <a target="_blank" href="https://www.amazon.it/gp/product/8861270239"                                                                                             class="list-group-item list-group-item-action book" >Black Jesus. The anthology</a>
    <a target="_blank" href="https://amzn.eu/d/bRTfh0T"                                                                                                               class="list-group-item list-group-item-action book" >Caccasutra - Guida tecnico-pratica all'emissione del caccone perfetto</a>
    <a target="_blank" href="https://youtu.be/rBK_NmAp3Js"                                                                                                            class="list-group-item list-group-item-action book" >Dracula <span class="label label-info">Audiobook Ita</span></a>
    <div class="list-group-item list-group-item-action dropdown" style="background-color: inherit;" >
      <button class="btn btn-link dropdown-toggle book" type="button" data-toggle="dropdown" style="border: none; padding-left: 0;color: white;">
        Foundation Novels
        <span class="caret"></span></button>
      <ul class="dropdown-menu" style="background-color: #323232; width: 100%; padding: 0px 0px 0px 0px;">
        <li>  <a target="_blank" href="https://youtu.be/77bkeNuYLFs" class="list-group-item list-group-item-action book" >Foundation <span class="label label-info">Audiobook Ita</span></a></li>
        <li>  <a target="_blank" href="https://youtu.be/0bddR1EIenE" class="list-group-item list-group-item-action book" >Foundation & Empire <span class="label label-info">Audiobook Ita</span></a></li>
        <li>  <a target="_blank" href="https://youtu.be/lDipzjHt0Ds" style=" display: inline-block; width: 50%" class="list-group-item list-group-item-action book" >Foundation & Earth - Pt 1 <span class="label label-info">Audiobook Ita</span></a><a target="_blank" href="https://youtu.be/oQKV2-t0CLM" class="list-group-item list-group-item-action book" style="display: inline-block; width: 50%">Foundation & Earth - Pt 2 <span class="label label-info">Audiobook Ita</span></a></li>
        <li>  <a target="_blank" href="https://www.youtube.com/watch?v=KofSMmhWr74" class="list-group-item list-group-item-action book" >Second Foundation <span class="label label-info">Audiobook Ita</span></a></li>
        <li>  <a target="_blank" href="https://youtu.be/SA8zWPY5Yqc" style=" display: inline-block; width: 50%" class="list-group-item list-group-item-action book" >Foundation's Edge - Pt 1 <span class="label label-info">Audiobook Ita</span></a><a target="_blank" href="https://youtu.be/o1V8x9FeH_M" class="list-group-item list-group-item-action book" style="display: inline-block; width: 50%">Foundation's Edge - Pt 2 <span class="label label-info">Audiobook Ita</span></a></li>
      </ul>
    </div>
    <a target="_blank" href="https://youtu.be/P_v0nsSe2Ro"                                                                                                            class="list-group-item list-group-item-action book" >Gateway <span class="label label-info">Audiobook Ita</span></a>
    <a target="_blank" href="https://www.amazon.it/Ghibliotheque-Unofficial-Movies-Studio-Ghibli/dp/1787396657"                                                       class="list-group-item list-group-item-action book" >Ghiblioteque</a>
    <a target="_blank" href="https://en.wikipedia.org/wiki/Harry_Potter"                                                                                              class="list-group-item list-group-item-action book" >Harry Potter</a>
    <a target="_blank" href="https://en.wikipedia.org/wiki/Homo_Deus:_A_Brief_History_of_Tomorrow"                                                                    class="list-group-item list-group-item-action book" >Homo Deus: A Brief History of Tomorrow</a>
    <a target="_blank" href="https://www.amazon.com/Cats-Disappeared-World-Genki-Kawamura/dp/1509889175"                                                              class="list-group-item list-group-item-action book" >If Cats Disappeared From the World</a>
    <a target="_blank" href="https://www.amazon.co.uk/Lingegno-tenebre-Leonardo-Michelangelo-Rinascimento/dp/B09YD1FLJN"                                              class="list-group-item list-group-item-action book" >L'Ingegno e le Tenebre <span class="label label-info">Audiobook Ita</span></a>
    <a target="_blank" href="https://www.amazon.it/genio-non-esiste-volte-idiota/dp/8899684693"                                                                       class="list-group-item list-group-item-action book" >Il Genio Non Esiste (e a volte è un idiota)</a>
    <a target="_blank" href="https://www.amazon.it/monaco-amava-gatti-sette-rivelazioni/dp/8820070782"                                                                class="list-group-item list-group-item-action book" >Il Monaco Che Amava I Gatti. Le Sette Rivelazioni</a>
    <a target="_blank" href="https://www.amazon.it/vulcano-musicali-Domenico-intervistato-Puracchio/dp/8899813302"                                                    class="list-group-item list-group-item-action book" >Il vulcano, Schana Wana e altri mondi musicali. Domenico Bini intervistato da Stefano Orlando Puracchio</a>
    <a target="_blank" href="https://www.amazon.it/gp/product/1521369038"                                                                                             class="list-group-item list-group-item-action book" >Informattica: informatica da matti per matti che fan informatica</a>
    <a target="_blank" href="https://www.amazon.co.uk/Io-trafficante-virus-scienza-giustizia/dp/B09XBRXYG6/ref=tmm_aud_swatch_0?_encoding=UTF8&qid=&sr="              class="list-group-item list-group-item-action book" >Io, trafficante di virus. Una storia di scienza e di amara giustizia <span class="label label-info">Audiobook Ita</span></a>
    <a target="_blank" href="https://www.amazon.co.uk/Immune-Journey-Mysterious-System-Keeps/dp/0593241312"                                                           class="list-group-item list-group-item-action book" >Immune: A Journey into the Mysterious System That Keeps You Alive</a>
    <a target="_blank" href="https://en.wikipedia.org/wiki/Lords_of_Chaos_(book)"                                                                                     class="list-group-item list-group-item-action book" >Lords of Chaos</a>
    <a target="_blank" href="https://youtu.be/VrT7z6owQds"                                                                                                            class="list-group-item list-group-item-action book" >Lord of the Flies <span class="label label-info">Audiobook Ita</span></a>
    <a target="_blank" href="https://www.amazon.co.uk/Marvel-Platinum-Definitive-Carnage-Various/dp/1846533791/"                                                      class="list-group-item list-group-item-action book" >Marvel Platinum: The Definitive Carnage</a>
    <a target="_blank" href="https://www.amazon.it/dp/B099NSRVFY"                                                                                                     class="list-group-item list-group-item-action book" >MinuteEarth Explains: How Did Whales Get So Big? And Other Curious Questions about Animals, Nature, Geology, and Planet Earth</a>
    <a target="_blank" href="https://en.wikipedia.org/wiki/Old_Man_Logan"                                                                                             class="list-group-item list-group-item-action book" >Old Man Logan</a>
    <a target="_blank" href="https://en.wikipedia.org/wiki/Pale_Blue_Dot_(book)"                                                                                      class="list-group-item list-group-item-action book" >Pale Blue Dot</a>
    <a target="_blank" href="https://amzn.eu/d/1CyQisi"                                                                                                               class="list-group-item list-group-item-action book" >Quaderni dalla terra piatta: Volume 1 - Cambio di Paradigma</a>
    <a target="_blank" href="https://www.amazon.it/Audible-Questa-%C3%A8-lAmerica/dp/B09MDL8QQ7"                                                                      class="list-group-item list-group-item-action book" >Questa è l'America <span class="label label-info">Audiobook Ita</span></a>
    <div class="list-group-item list-group-item-action dropdown" style="background-color: inherit;" >
      <button class="btn btn-link dropdown-toggle book" type="button" data-toggle="dropdown" style="border: none; padding-left: 0;color: white;">
        Robot Series
        <span class="caret"></span></button>
      <ul class="dropdown-menu" style="background-color: #323232; width: 100%; padding: 0px 0px 0px 0px;">
        <li>  <a target="_blank" href="https://youtu.be/fgcY19Rkt5s"                                            class="list-group-item list-group-item-action book" >The Caves of Steel <span class="label label-info">Audiobook Ita</span></a></li>
        <li>  <a target="_blank" href="https://www.youtube.com/watch?v=nIB-kYEvmG0"                             class="list-group-item list-group-item-action book" >The Naked Sun <span class="label label-info">Audiobook Ita</span></a></li>
        <li>  <a target="_blank" href="https://youtu.be/y6hcgIw8zEM" style="display: inline-block; width: 50%"  class="list-group-item list-group-item-action book" >The Robots of Dawn - Pt 1 <span class="label label-info">Audiobook Ita</span></a><a target="_blank" href="https://youtu.be/-kpk1zqH0-k" class="list-group-item list-group-item-action book" style="display: inline-block; width: 50%">The Robots of Dawn - Pt 2 <span class="label label-info">Audiobook Ita</span></a></li>
      </ul>
    </div>
    <a target="_blank" href="https://www.amazon.it/Saggio-erotico-commedia-disastro-ambientale/dp/8804731176"                                                         class="list-group-item list-group-item-action book" >Saggio erotico sulla fine del mondo. La commedia brutta del disastro ambientale</a>
    <a target="_blank" href="https://en.wikipedia.org/wiki/Shannara"                                                                                                  class="list-group-item list-group-item-action book" >Shannara</a>
    <a target="_blank" href="https://en.wikipedia.org/wiki/Star_Wars:_Episode_I_%E2%80%93_The_Phantom_Menace_(novel)"                                                 class="list-group-item list-group-item-action book" >Star Wars: Episode I - The Phantom Menace (novel)</a>
    <a target="_blank" href="https://audiobookss.com/free-full-audiobook-start-with-why-by-simon-sinek.html"                                                          class="list-group-item list-group-item-action book" >Start With Why <span class="label label-warning">Audiobook Eng</span></a>
    <div class="list-group-item list-group-item-action dropdown" style="background-color: inherit;" >
      <button class="btn btn-link dropdown-toggle book" type="button" data-toggle="dropdown" style="border: none; padding-left: 0;color: white;">
        The Century Trilogy
        <span class="caret"></span></button>
      <ul class="dropdown-menu" style="background-color: #323232; width: 100%; padding: 0px 0px 0px 0px;">
        <li>  <a target="_blank" href="https://t.me/c/1383142505/1331"   class="list-group-item list-group-item-action book" >Fall of Giants <span class="label label-info">Audiobook Ita</span></a></li>
        <li>  <a target="_blank" href="https://t.me/c/1383142505/1335"   class="list-group-item list-group-item-action book" >Winter of the World <span class="label label-info">Audiobook Ita</span></a></li>
        <li>  <a target="_blank" href="https://t.me/c/1383142505/1347"   class="list-group-item list-group-item-action book" >Edge of Eternity <span class="label label-info">Audiobook Ita</span></a></li>
      </ul>
    </div>
    <a target="_blank" href="https://youtu.be/CT0PS9hAeso"                                                                 style="display: inline-block; width: 50%"  class="list-group-item list-group-item-action book" >The Complete Robot - Pt 1 <span class="label label-info">Audiobook Ita</span></a><a target="_blank" href="https://youtu.be/WHMMqUBcXs0" class="list-group-item list-group-item-action book" style="display: inline-block; width: 50%">The Complete Robot - Pt 2 <span class="label label-info">Audiobook Ita</span></a>
    <a target="_blank" href="https://www.youtube.com/watch?v=0VHNQjOvHnA"                                                                                             class="list-group-item list-group-item-action book" >The End of Eternity <span class="label label-info">Audiobook Ita</span></a>
    <a target="_blank" href="./articles/2021-12-03-godsThemselvesInstructions.html"                                                                                   class="list-group-item list-group-item-action book" >The God Themselves <span class="label label-warning">Audiobook Eng</span></a>
    <div class="list-group-item list-group-item-action dropdown" style="background-color: inherit;" >
      <button class="btn btn-link dropdown-toggle book" type="button" data-toggle="dropdown" style="border: none; padding-left: 0;color: white;">
        The Hitchhiker's Guide to the Galaxy
        <span class="caret"></span></button>
      <ul class="dropdown-menu" style="background-color: #323232; width: 100%; padding: 0px 0px 0px 0px;">
        <li><a target="_blank" href="https://www.youtube.com/watch?v=0ssU79thtoA"                            class="list-group-item list-group-item-action book" >The Hitchhiker's Guide to the Galaxy <span class="label label-warning">Audiobook Eng</span></a></li>
        <li><a target="_blank" href="https://youtube.com/playlist?list=PLzkVXRJZIjCDO3d7kgZnJHbzBD0lCCx9Q"   class="list-group-item list-group-item-action book" >The Restaurant at the End of the Universe <span class="label label-warning">Audiobook Eng</span></a></li>
        <li><a target="_blank" href="https://youtube.com/playlist?list=PLSoD2CcPrumF2kCC4jhiUcnWiYkypgv8Y"   class="list-group-item list-group-item-action book" >Life, the Universe and Everything <span class="label label-warning">Audiobook Eng</span></a></li>
        <li><a target="_blank" href="https://youtube.com/playlist?list=PLSoD2CcPrumEwDGKG3MzBwS95BZjqM9bo"   class="list-group-item list-group-item-action book" >So Long and Thanks for All the Fish <span class="label label-warning">Audiobook Eng</span></a></li>
        <li><a target="_blank" href="https://youtube.com/playlist?list=PLSoD2CcPrumFXN4hnD1jPLZXYsAWK2O9V"   class="list-group-item list-group-item-action book" >Mostly Harmless <span class="label label-warning">Audiobook Eng</span></a></li>
      </ul>
    </div>
    <a target="_blank" href="https://en.wikipedia.org/wiki/The_Hobbit"                                               class="list-group-item list-group-item-action book"                                    >The Hobbit</a>
    <a target="_blank" href="https://en.wikipedia.org/wiki/The_Hunger_Games"                                         class="list-group-item list-group-item-action book"                                    >The Hunger Games</a>
    <a target="_blank" href="https://www.amazon.com/Inner-Game-Music-Barry-Green/dp/0385231261"                      class="list-group-item list-group-item-action book"                                    >The Inner Game of Music</a>
    <div class="list-group-item list-group-item-action dropdown" style="background-color: inherit;" >
      <button class="btn btn-link dropdown-toggle book" type="button" data-toggle="dropdown" style="border: none; padding-left: 0;color: white;">
        The Kingsbridge Novels
        <span class="caret"></span></button>
      <ul class="dropdown-menu" style="background-color: #323232; width: 100%; padding: 0px 0px 0px 0px;">
        <li><a target="_blank"   href="https://en.wikipedia.org/wiki/The_Pillars_of_the_Earth"          class="list-group-item list-group-item-action book" >The Pillars of the Earth</a></li>
        <li><a target="_blank"   href="https://en.wikipedia.org/wiki/World_Without_End_(Follett_novel)" class="list-group-item list-group-item-action book" >World Without End</a></li>
        <li><a target="_blank"   href="https://en.wikipedia.org/wiki/A_Column_of_Fire"                  class="list-group-item list-group-item-action book" >A Column of Fire</a></li>
        <li><a target="_blank"   href="https://en.wikipedia.org/wiki/The_Evening_and_the_Morning"       class="list-group-item list-group-item-action book" >The Evening and the Morning</a></li>
      </ul>
    </div>
    <a target="_blank" href="https://en.wikipedia.org/wiki/The_Lord_of_the_Rings"                                    class="list-group-item list-group-item-action book"                                    >The Lord of the Rings</a>
    <a target="_blank" href="https://www.amazon.co.uk/Marvel-Book-Expand-Knowledge-Universe/dp/0241357659"           class="list-group-item list-group-item-action book"                                    >The Marvel Book: Expand Your Knowledge Of A Vast Comics Universe</a>
    <a target="_blank" href="https://youtu.be/zJsQK6ZUeIY"                                                           class="list-group-item list-group-item-action book"                                    >The Master and Margarita <span class="label label-info">Audiobook Ita</span></a>
    <a target="_blank" href="https://www.amazon.co.uk/Patient-Equation-Data-Driven-Precision-Medicine/dp/111962214X" class="list-group-item list-group-item-action book"                                    >The Patient Equation: The Precision Medicine Revolution in the Age of COVID-19 and Beyond</a>
    <a target="_blank" href="https://en.wikipedia.org/wiki/The_Problem_of_Cell_13"                                   class="list-group-item list-group-item-action book"                                    >The Problem of Cell 13</a>
    <a target="_blank" href="https://www.amazon.co.uk/Star-Wars-Book-Expand-knowledge/dp/0241409977"                 class="list-group-item list-group-item-action book"                                    >The Star Wars Book: Expand Your Knowledge of a Galaxy Far, Far Away</a>
    <a target="_blank" href="https://www.amazon.co.uk/Storyteller-Tales-Life-Music/dp/1398503703"                    class="list-group-item list-group-item-action book"                                    >The Storyteller: Tales of Life and Music</a>
    <a target="_blank" href="https://www.amazon.co.uk/Venezia-Metal-Italian-Marco-Crescizz-ebook/dp/B09MS9PCYK"      class="list-group-item list-group-item-action book"                                    >Venezia Metal</a>
    <a target="_blank" href="https://smunix.github.io/dev.stephendiehl.com/hask/tutorial.pdf"                        class="list-group-item list-group-item-action book"                                    >What I Wish I Knew When Learning Haskell</a>
  </ul>
#+END_EXPORT

** Wanna Read

  Legend:
  #+BEGIN_EXPORT HTML
  <ul>
    <li><span style="background-color:red;">Red:</span> means it's, probably a manga to read online, do not purchase if not strictly necessary.</li>
    <li><span style="background-color:blue;">Blue:</span> means the book is already purchased, but it didn't arrive or wasn't archivied yet. Don't buy.</li>
    <li><span style="background-color:purple;">Purple:</span> means the book is awailable online for free. Don't buy.</li>
  </ul>
  #+END_EXPORT


#+BEGIN_EXPORT HTML
<p id="totalBookCount"></p>
<ul id="wanna_read_bookList" class="list-group">
  <a target="_blank" href="https://en.wikipedia.org/wiki/23_Things_They_Don%27t_Tell_You_About_Capitalism"                                    class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">23 Things They Don't Tell You About Capitalism</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/Monster-Calls-Patrick-Ness/dp/1406361801"                                                 class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">A Monster Calls</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/Agile-Good-Hype-Bertrand-Meyer/dp/3319051547"                                             class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Agile!: The Good, the Hype and the Ugly</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/Algorithms-Live-Computer-Science-Decisions/dp/1627790365"                                 class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Algorithms to Live By: The Computer Science of Human Decisions</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Battle_Angel_Alita"                                                                  class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:red;">Alita</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/New-Guide-Science-Isaac-Asimov/dp/0670803472"                                             class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Asimov's New Guide to Science</p></a>
  <a target="_blank" href="https://www.amazon.com/Short-History-Nearly-Everything/dp/076790818X"                                              class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">A Short History of Nearly Everything</p></a>
  <a target="_blank" href="https://www.amazon.com/Astrophysics-People-Hurry-deGrasse-Tyson/dp/0393609391"                                     class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Astrophysics for People in a Hurry</p></a>
  <a target="_blank" href="https://berserk-read.online/"                                                                                      class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:red;">Berserk</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Black_Torch"                                                                         class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:red;">Black Torch</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Black_Metal:_Evolution_of_the_Cult"                                                  class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Black Metal: Evolution Of The Cult</p></a>
  <a target="_blank" href="https://abuseofnotation.github.io/category-theory-illustrated/"                                                    class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Category Theory Illustrated</p></a>
  <a target="_blank" href="https://mangabuddy.com/claymore"                                                                                   class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:red;">Claymore</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Chaos:_Making_a_New_Science"                                                         class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Chaos: Making a New Science</p></a>
  <a target="_blank" href="https://amzn.eu/d/crRvCjf"                                                                                         class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:blue;">Carnage: Volume 1: In The Court Of Crimson</p></a>
  <a target="_blank" href="https://amzn.eu/d/iMNSGJ3"                                                                                         class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:red;">Carnage: Reigns</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Cathedral_of_the_Sea"                                                                class="list-group-item list-group-item-action wa_book">Cathedral of the Sea</a>
  <a target="_blank" href="https://www.amazon.com/CommitStrip-Rise-Coders-Issartial/dp/2954706228"                                            class="list-group-item list-group-item-action wa_book">CommitStrip: Rise of the Coders</a>
  <a target="_blank" href="https://www.amazon.co.uk/Complete-Learn-Guitar-Chords-Manual/dp/1864693177"                                        class="list-group-item list-group-item-action wa_book">Complete Learn to Play Guitar Chords Manual</a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Contact_(novel)"                                                                     class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Contact</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Dune_(franchise)#Plot_arc"                                                           class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Dune</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Fahrenheit_451"                                                                      class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Fahrenheit 451</p></a>
  <a target="_blank" href="https://it.wikipedia.org/wiki/Fantozzi_(romanzo)#Romanzi_di_Fantozzi"                                              class="list-group-item list-group-item-action wa_book">Fantozzi</a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Flowers_for_Algernon"                                                                class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Flowers for Algernon</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Forward_the_Foundation"                                                              class="list-group-item list-group-item-action wa_book">Forward the Foundation</a>
  <a target="_blank" href="https://mitpress.mit.edu/9780262019347/functional-differential-geometry/"                                          class="list-group-item list-group-item-action wa_book">Functional Differential Geometry</a>
  <a target="_blank" href="https://amzn.eu/d/h4bxkuc"                                                                                         class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Guitar for Dummies</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/His_Dark_Materials"                                                                  class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">His Dark Materials</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/How-Listen-Jazz-Ted-Gioia/dp/0465060897"                                                  class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">How to Listen to Jazz</p></a>
  <a target="_blank" href="https://www.amazon.com/stratagemmi-segreta-strategia-trionfare-quotidiana/dp/8880937006"                           class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">I Trentasei Stratagemmi</p></a>
  <a target="_blank" href="https://mitpress.mit.edu/books/ideas-created-future"                                                               class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Ideas That Created the Future</p></a>
  <a target="_blank" href="https://www.amazon.it/scienza-della-casa-Ruggero-Rollini/dp/8804755326"                                            class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">C'è Chimica in Casa</p></a>
  <a target="_blank" href="https://amzn.eu/d/1Owu7gW"                                                                                         class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Il Coraggio di Non Piacere</p></a>
  <a target="_blank" href="https://www.amazon.it/dp/886431024X"                                                                               class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Il Metodo Sticazzi</p></a>
  <a target="_blank" href="https://www.amazon.it/Famiglie-bestiali-Willy-Guasti/dp/8817163538"                                                class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Il Coccodrillo ha il Cuore Tenero</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/Imparare-tecnica-suono-Marco-Sacco/dp/1505563542"                                         class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Imparare la Tecnica del Suono</p></a>
  <a target="_blank" href="https://amzn.eu/d/1UhscYJ"                                                                                         class="list-group-item list-group-item-action wa_book">Istruzioni per Rendersi Infelici</a>
  <a target="_blank" href="https://www.amazon.co.uk/LAvvocato-dellAtomo-Italian-Luca-Romano-ebook/dp/B09X1VLTBV"                              class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">L'Avvocato dell'Atomo</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/scienza-carne-chimica-bistecca-dellarrosto/dp/8858016025"                                 class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">La Scienza della Carne</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/Scienza-della-pasticceria-Dario-Bressanini/dp/8858012305"                                 class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">La Scienza della Pasticceria</p></a>
  <a target="_blank" href="https://www.amazon.it/scienza-pulizie-detersivo-candeggina-bicarbonato/dp/8858043030/"                             class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">La Scienza delle Pulizie</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/SCIENZA-DELLE-VERDURE-BRESSANINI-D/dp/8858025199"                                         class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">La Scienza delle Verdure</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/Princess-Mononoke-First-Story/dp/1421575868"                                              class="list-group-item list-group-item-action wa_book">La Tua Bestemmia Quotidiana</a>
  <a target="_blank" href="https://www.amazon.it/dp/B0B2TTVNFX/"                                                                              class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">La tempesta imperfetta. Viaggio nella mente di chi crede alle fake news: noi</p></a>
  <a target="_blank" href="https://www.amazon.it/dp/B00N2OTG24/?coliid=I2XP5VZI7M52U4&colid=22QBHENP44UR0&psc=0&ref_=lv_ov_lig_dp_it"         class="list-group-item list-group-item-action wa_book">Le corde vibranti, l'orecchio, la musica</a>
  <a target="_blank" href="https://www.amazon.com/Learn-Physics-Functional-Programming-Hands/dp/1718501668"                                   class="list-group-item list-group-item-action wa_book">Learn Physics with Functional Programming: A Hands-on Guide to Exploring Physics with Haskell</a>
  <a target="_blank" href="https://www.amazon.it/dp/B00A83G6ZC/?coliid=I1IVLGELZ7UQAP&colid=22QBHENP44UR0&psc=0&ref_=lv_ov_lig_dp_it"         class="list-group-item list-group-item-action wa_book">Libertà vigilata: Privacy, sicurezza e mercato nella rete</a>
  <a target="_blank" href="https://www.amazon.co.uk/Libro-Italian-Maccio-Capatonda-ebook/dp/B08NDWD2J6"                                       class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Libro</p></a>
  <a target="_blank" href="https://www.amazon.it/dp/B0B3MDGT1V/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1"                                  class="list-group-item list-group-item-action wa_book">Libro 2</a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Lolita"                                                                              class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Lolita</p></a>
  <a target="_blank" href="https://madeinabyss-manga-new.com/"                                                                                class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:red;">Made in Abyss</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/Marvel-Platinum-Definitive-Wolverine-Reloaded/dp/1846535379"                              class="list-group-item list-group-item-action wa_book">Marvel Platinum: The Definitive Wolverine Reloaded</a>
  <a target="_blank" href="https://amzn.eu/d/ct2s0rp"                                                                                         class="list-group-item list-group-item-action wa_book">Marvel Villains: Carnage</a>
  <a target="_blank" href="https://store.heavymusicartwork.com/collections/books/products/mondo-black"                                        class="list-group-item list-group-item-action wa_book">Mondo Black</a>
  <a target="_blank" href="https://store.heavymusicartwork.com/products/mondo-death"                                                          class="list-group-item list-group-item-action wa_book">Mondo Death</a>
  <a target="_blank" href="https://mitpress.mit.edu/books/musimathics-volume-1"                                                               class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Musimathics - Vol 1</p></a>
  <a target="_blank" href="https://mitpress.mit.edu/books/musimathics-volume-2"                                                               class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Musimathics - Vol 2</p></a>
  <a target="_blank" href="https://www.amazon.it/dp/8823851270/?coliid=IR418QZ13T9Y0&colid=22QBHENP44UR0&psc=1&ref_=lv_ov_lig_dp_it"          class="list-group-item list-group-item-action wa_book">Oltre le occasioni perdute. Dal transistor allo smartphone. 60 anni di storia in presa diretta</a>
  <a target="_blank" href="https://www.amazon.it/dp/0141043024/?coliid=I2HGVZMJBML81R&colid=22QBHENP44UR0&psc=1&ref_=lv_ov_lig_dp_it"         class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Outliers. The story of success</p></a>
  <a target="_blank" href="https://www.amazon.it/PERCH%C3%89-CACHIAMO-immersivo-meraviglioso-dellespulsione/dp/B09TWB1CN3"                    class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Perché Cachiamo</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Prelude_to_Foundation"                                                               class="list-group-item list-group-item-action wa_book">Prelude to Foundation</a>
  <a target="_blank" href="https://promisedneverland.com/"                                                                                    class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:red;">Promised Neverland - from Volume 38</p></a>
  <a target="_blank" href="https://amzn.eu/d/7wnJ2P2"                                                                                         class="list-group-item list-group-item-action wa_book">Quaderni dalla Terra Piatta: Volume 2: una Immane Ondata</a>
  <a target="_blank" href="https://rickbeato.com/products/the-beato-book-interactive?_pos=1&_sid=20fbc9b6e&_ss=r"                             class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Rick Beato Book</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Remembrance_of_Earth%27s_Past"                                                       class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Remembrance of Earth's Past Trilogy</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Scythe_(novel)"                                                                      class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Scythe</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Snow_Crash"                                                                          class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Snow Crash</p></a>
  <a target="_blank" href="https://www.amazon.com/Spillover-Animal-Infections-Human-Pandemic/dp/0393346617"                                   class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Spillover: Animal Infections and the Next Human Pandemic</p></a>
  <a target="_blank" href="https://www.kickstarter.com/projects/bitbotmedia/legacy-of-kain-soul-reaver-prequel-graphic-novel"                 class="list-group-item list-group-item-action wa_book">Soul Reaver: The Dead Shall Rise</a>
  <a target="_blank" href="https://www.amazon.co.uk/Starry-Messenger-Cosmic-Perspectives-Civilisation/dp/0008543186"                          class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Starry Messenger: Cosmic Perspectives on Civilization</p></a>
  <a target="_blank" href="https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book.html"                                        class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Structure and Interpretation of Computer Programs</p></a>
  <a target="_blank" href="https://mitp-content-server.mit.edu/books/content/sectbyfn/books_pres_0/9579/sicm_edition_2.zip/book.html"         class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Structure and Interpretation of Classical Mechanics</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Surely_You%27re_Joking,_Mr._Feynman!"                                                class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Surely You're Joking, Mr. Feynman!</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/The_Age_of_Intelligent_Machines"                                                     class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">The Age of Intelligent Machines</p></a>
  <a target="_blank" href="https://amzn.eu/d/9Gcdtbs"                                                                                         class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">The Armour of Light</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/The_Dark_Tower_(series)"                                                             class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">The Dark Tower</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/History-Jazz-Ted-Gioia/dp/0195399706"                                                     class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">The History of Jazz</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/Influential-Mind-Reveals-Change-Others/dp/1408706067"                                     class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">The Influential Mind: What the Brain Reveals About Our Power to Change Others</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/Jazz-Theory-Book-Mark-Levine/dp/1883217040"                                               class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">The Jazz Theory Book</p></a>
  <a target="_blank" href="https://natureofcode.com/"                                                                                         class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">The Nature of Code</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/The_Witcher"                                                                         class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">The Witcher</p></a>
  <a target="_blank" href="https://smile.amazon.co.uk/dp/0670921394/ref=cm_sw_r_cp_apa_i_b8P7EbV4ZEJ14"                                       class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">The World Beyond Your Head: How to Flourish in an Age of Distraction</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/The_Vampire_Chronicles"                                                              class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">The Vampire Chronicles</p></a>
  <a target="_blank" href="https://amzn.eu/8QIdizf"                                                                                           class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">There's a War Going On But No One Can See It: 'A brilliant page-turner'</p></a>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Thinking,_Fast_and_Slow"                                                             class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Thinking, Fast and Slow</p></a>
  <a target="_blank" href="https://www.amazon.it/dp/0791801624/?coliid=I25BGOMWA9LRH4&colid=22QBHENP44UR0&psc=0&ref_=lv_ov_lig_dp_it"         class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Unwritten Laws of Engineering</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/What-If-Scientific-Hypothetical-Questions/dp/1848549563"                                  class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">What If?: Serious Scientific Answer to Absurd Hypothetical Questions: Serious Scientific Answers to Absurd Hypothetical Questions</p></a>
  <a target="_blank" href="https://www.amazon.co.uk/What-Additional-Scientific-Hypothetical-Questions/dp/147368062X"                          class="list-group-item list-group-item-action wa_book">What If?2: Additional Serious Scientific Answers to Absurd Hypothetical Questions</a>
  <a target="_blank" href="https://www.amazon.co.uk/What-We-Owe-Future-Million-Year/dp/0861542509/ref=sr_1_1?keywords=what+we+owe+the+future" class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">What We Owe The Future: A Million-Year View</p></a>
  <a target="_blank" href="https://www.amazon.it/dp/068483877X/?coliid=I2WOXTJ78H39UD&colid=22QBHENP44UR0&psc=1&ref_=lv_ov_lig_dp_it"         class="list-group-item list-group-item-action wa_book"><p style="display:inline;background-color:purple;">Zen Guitar</p></a>
<h1></h1>
</ul>
#+END_EXPORT

#+begin_export html
<script type="text/javascript">
$(function() {
  $('#text-table-of-contents > ul li').first().css("display", "none");
  $('#text-table-of-contents > ul li:nth-child(2)').first().css("display", "none");
  $('#table-of-contents').addClass("visible-lg")
  $('#totalBookCount').text("Total Books: " + $('.book').length)
});
</script>
#+end_export
