name: Github Page CI

on:
  push:
    branches:
        - "**"


jobs:
  check_urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install curl build-essential -y
      - name: Link Checker
        run: |
          npx http-server -p 8080 &
          sleep 1
          npx broken-link-checker -r -o -requests 5 --exclude twitter --exclude linkedin --input http://localhost:8080/
