name: Github Page CI

on:
  push:
    branches:
        - "**"


jobs:
  check_urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          # Twitter, Linkedin and mailto doesn't seems to be reachable even if they work 🤔
          args: . --exclude "(https.*twitter\.com.*|https.*linkedin\.com.*|.*benkio89\@gmail\.com.*)"  --accept 200,429
          fail: true
