name: Github Page CI

on:
  push:
    branches:
        - "**"


jobs:
  check_urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Act dependencies
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install sudo -y
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install curl build-essential -y
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          # Twitter, Linkedin and mailto doesn't seems to be reachable even if they work 🤔
          args: --base . --exclude "(https.*twitter\.com.*|https.*linkedin\.com.*|.*benkio89\@gmail\.com.*)"  --accept 200,429 --no-progress './**/*.html'
          fail: true
          format: json
          
